/*
Cloud DNS

Testing RecordsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dnsclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_dnsclient_RecordsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RecordsAPIService CreateRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var zoneId string

		resp, httpRes, err := apiClient.RecordsAPI.CreateRecord(context.Background(), tenantId, zoneId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordsAPIService DeleteRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var zoneId string
		var recordId string

		httpRes, err := apiClient.RecordsAPI.DeleteRecord(context.Background(), tenantId, zoneId, recordId).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordsAPIService GetRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var zoneId string
		var recordId string

		resp, httpRes, err := apiClient.RecordsAPI.GetRecord(context.Background(), tenantId, zoneId, recordId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordsAPIService GetRecords", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var zoneId string

		resp, httpRes, err := apiClient.RecordsAPI.GetRecords(context.Background(), tenantId, zoneId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RecordsAPIService UpdateRecord", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var zoneId string
		var recordId string

		resp, httpRes, err := apiClient.RecordsAPI.UpdateRecord(context.Background(), tenantId, zoneId, recordId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
