/*
Cloud DNS

Testing AuditsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package dnsclient

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_dnsclient_AuditsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test AuditsAPIService GetAudits", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var tenantId string
		var zoneId string

		resp, httpRes, err := apiClient.AuditsAPI.GetAudits(context.Background(), tenantId, zoneId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
